### ISSUE TITLE
When I use Ubuntu image, nothing is displayed,

### ISSUE THREAD

**Issue by bebee** [linuxserver/docker-webtop#13]
my os mac 10.15.7 (19H1030)
my docker destop version is 3.3.3 
it  is currently the newest version available

this is my docker-compuse.yml   
When I use alpine image ,everything is ok
but when i use ubuntu image,nothing is displayed

```
version: "3"
services:
  webtop:
    image: ghcr.io/linuxserver/webtop:ubuntu-kde

    container_name: webtop
    privileged: true #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
    shm_size: "5gb" #optional
    restart: unless-stopped

  caddy:
    image : caddy:2.3.0-alpine
    ports:
     - "80:80"
    
    depends_on:
     - webtop
    volumes:
     - ./caddy/data:/data
     - ./caddy/config:/config
     - ./caddy/Caddyfile:/etc/caddy/Caddyfile

```
