### ISSUE TITLE
[FEAT] Xorg GPU acceleration

### ISSUE THREAD

**Issue by msinfo32github** [linuxserver/docker-webtop#241]
### Is this a new feature request?

- [x] I have searched the existing issues

### Wanted change

- Optionally allow GPU usage to be used for KasmVNC session

### Reason for change

- This should reduce CPU usage of the container when in-use as llvmpipe does not need to be used by xorg. Instead, this should be handled by the GPU driver (as far as I can tell) to render xorg
- When moving applications around the desktop, while monitoring CPU usage with htop, it shows that the CPU usage is increased almost to 40% usage just by moving a window around. This behaviour can also be seen with any video playback or anything graphically-heavy.

**Comment by aptalca** [comment]
It already supports it
https://github.com/linuxserver/docker-webtop?tab=readme-ov-file#optional-run-configurations

**Comment by msinfo32github** [comment]
This looks like something that may be supported within KasmVNC.

The [documentation](https://www.kasmweb.com/kasmvnc/docs/master/man/Xvnc.html) says this:

> -hw3d
Enable hardware 3d acceleration. Default is software (llvmpipe usually).

Also, within the README.md for [kasmtech/KasmVNC](https://github.com/kasmtech/KasmVNC/blob/511e2ae542e95f5447a0a145bb54ced968e6cfec/README.md?plain=1#L105) has a configuration option for `hd3d: false`.

**Comment by msinfo32github** [comment]
It seems that this is something that can be configured in `~/.vnc/kasmvnc.yaml`. However, from my testing with the following configuration it does not seem to make any changes.
```yaml
desktop:
  gpu:
    hw3d: true
    drinode: /dev/dri/renderD128
```

**Comment by msinfo32github** [comment]
Did not see your reply until now weirdly. I'll look into this, thanks!

**Comment by msinfo32github** [comment]
I believe that I am already using this?

Here is my `docker-compose.yml` file.

```yaml
---
services:
  webtop:
    image: linuxserver/webtop:latest
    container_name: webtop-02
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBFOLDER=/ #optional
      - TITLE=Webtop 02 #optional
      - DRINODE=/dev/dri/renderD128
    volumes:
      - ./:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
```

I can confirm that the GPU is seen in the webtop as this shows up when using `glxgears -info`
