### ISSUE TITLE
[FEAT] make AppImage to work by default

### ISSUE THREAD

**Issue by tomaszduda23** [linuxserver/docker-webtop#261]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

add libfuse2 by default to let AppImage mount file system

### Reason for change

many apps is distributed as AppImage

### Proposed code change

apt install libfuse2

**Comment by thelamer** [comment]
What about /dev/fuse? And how do you run mount inside of the container.
This is not just missing package, it is about privving the container way up.

**Comment by tomaszduda23** [comment]
It can be done in docker compose. It could be mentioned in documentation.
```
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - label:disable
    devices:
      - /dev/fuse:/dev/fuse
```
