### ISSUE TITLE
[BUG] International keyboards unsupported

### ISSUE THREAD

**Issue by DL6ER** [linuxserver/docker-webtop#326]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Previously, with kasmvnc, it was no problem to use `webtop` with international keyboards, like the German `QWERTZ` layout. Now, there is no option and when typing `Z` on the keyboard, `Y` appears on `webtop`, similarly, most multi-key strokes (secondary level characters) stopped working, e.g., <kbd>Alt Gr</kbd> + <kbd>Q</kbd> = `@` doesn't work at all.

### Expected Behavior

`webtop` should use the keys entered by the user, not assuming ANSI QWERTY layout.

### Steps To Reproduce

Use any keyboard layout that is not `QWERTY` on your system and observe that this is ignored in the container. **There was no issue with `kasmvnc`-based containers.**

### Environment

```markdown
- OS: doesn't matter (Ubuntu 24.04)
- How docker service was installed: doesn't matter (apt)
```

### CPU architecture

x86-64

### Docker creation

```bash
example script from https://docs.linuxserver.io/images/docker-webtop/
```

### Container logs

```bash
not relevant here
```

**Comment by DL6ER** [comment]
Related: https://github.com/selkies-project/selkies/issues/9

For me (and probably all international users), this means I will have to build the package myself locally from now on.

Please consider either reverting https://github.com/linuxserver/docker-webtop/pull/323 (and friends) or please offer the `kasmvnc` based alternative via an additional tag.

**Comment by Roxedus** [comment]
-e LC_ALL let's you set the keyboard, but it also currently sets the language of the application, if it looks for that variable.

**Comment by DL6ER** [comment]
No, unfortunately, not. I did already try
``` yaml
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest #alpine-xfce
    container_name: webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Europe/Berlin
      - LC_ALL=de_DE.UTF-8
      - SUBFOLDER=/ #optional
      - KEYBOARD=de-de-qwertz #optional
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "2gb" #optional
    restart: unless-stopped
```
but the keyboard in still QWERTY. When I revert to a `sha256` from, e.g., two weeks ago (with kasmvnc), everything is fine with the keyboard without any further changes to the `docker-compose.yml`. The container's language matching the corresponding country's language would be an acceptable compromise IMO.
